app:
    resource: "@BlogBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_user_security_login:
    pattern:  /login/
    defaults: { _controller: FOSUserBundle:Security:login }
    
fos_user_registration_register:
    pattern:  /register/
    defaults: { _controller: FOSUserBundle:Registration:register }

fos_user_registration_confirmed:
    pattern: /register/confirmed/
    defaults: { _controller: FOSUserBundle:Registration:confirmed }