app:
    resource: "@BlogBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_user_security_login:
    pattern:  /login/
    defaults: { _controller: FOSUserBundle:Security:login }

